# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x06RECUBE\"0\n\x0eLoginStatement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\x0c\x41\x63\x63ountState\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x10\n\x08LoginSCS\x18\x02 \x01(\x08\"%\n\x12\x43ontinuationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"*\n\x0f\x43ontinuationKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"Y\n\x07\x41\x63\x63ount\x12$\n\x05state\x18\xfa\x01 \x01(\x0b\x32\x14.RECUBE.AccountState\x12\x0e\n\x06\x61piKey\x18\x04 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"V\n\x16\x41\x63\x63ountCreateStatement\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\xfa\x01 \x01(\x0b\x32\x0f.RECUBE.Account2\xcd\x01\n\x0cLoginAccount\x12\x30\n\x05Login\x12\x16.RECUBE.LoginStatement\x1a\x0f.RECUBE.Account\x12@\n\x06SingUp\x12\x16.RECUBE.LoginStatement\x1a\x1e.RECUBE.AccountCreateStatement\x12I\n\x12\x43ontinuationSignal\x12\x17.RECUBE.ContinuationKey\x1a\x1a.RECUBE.ContinuationResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINSTATEMENT._serialized_start=25
  _LOGINSTATEMENT._serialized_end=73
  _ACCOUNTSTATE._serialized_start=75
  _ACCOUNTSTATE._serialized_end=123
  _CONTINUATIONRESULT._serialized_start=125
  _CONTINUATIONRESULT._serialized_end=162
  _CONTINUATIONKEY._serialized_start=164
  _CONTINUATIONKEY._serialized_end=206
  _ACCOUNT._serialized_start=208
  _ACCOUNT._serialized_end=297
  _ACCOUNTCREATESTATEMENT._serialized_start=299
  _ACCOUNTCREATESTATEMENT._serialized_end=385
  _LOGINACCOUNT._serialized_start=388
  _LOGINACCOUNT._serialized_end=593
# @@protoc_insertion_point(module_scope)
