# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recube.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecube.proto\x12\x06RECUBE\".\n\x0eloginStatement\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0cloginRespons\x12\r\n\x05state\x18\x01 \x01(\x08\"\x1d\n\nOneRespons\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x05Login\x12\x35\n\x05LOGIN\x12\x16.RECUBE.loginStatement\x1a\x14.RECUBE.loginResponsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recube_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINSTATEMENT._serialized_start=24
  _LOGINSTATEMENT._serialized_end=70
  _LOGINRESPONS._serialized_start=72
  _LOGINRESPONS._serialized_end=101
  _ONERESPONS._serialized_start=103
  _ONERESPONS._serialized_end=132
  _LOGIN._serialized_start=134
  _LOGIN._serialized_end=196
# @@protoc_insertion_point(module_scope)
